name: 'Vercel Deploy'
description: 'Deploy a Next.js app to Vercel using the Vercel CLI with environment input via pnpm dlx'

outputs:
  deployment-url:
    description: 'The deployment URL'
    value: ${{ steps.deploy-preview.outputs.deployment-url || steps.deploy-production.outputs.deployment-url }}
  inspect-url:
    description: 'The Vercel inspect URL'
    value: ${{ steps.deploy-preview.outputs.inspect-url || steps.deploy-production.outputs.inspect-url }}

inputs:
  environment:
    description: 'Target environment to deploy to (production or preview)'
    required: true

# Gets VERCEL_TOKEN from caller workflow secrets
runs:
  using: 'composite'
  steps:
    - name: Prepare Node project
      uses: ./.github/actions/prepare

    - name: Pull Vercel environment information
      shell: bash
      run: pnpm dlx vercel@latest pull --yes --environment "${{ inputs.environment }}" --token "$VERCEL_TOKEN"

    - name: Build
      shell: bash
      run: pnpm dlx vercel@latest build --token "$VERCEL_TOKEN"

    - name: Deploy to Vercel (preview)
      id: deploy-preview
      if: ${{ inputs.environment != 'production' }}
      shell: bash
      run: |
        set +e  # Don't exit on error
        output=$(pnpm dlx vercel@latest deploy --prebuilt --token "$VERCEL_TOKEN" 2>&1)
        exit_code=$?
        set -e  # Re-enable exit on error

        echo "Exit code: $exit_code"
        echo "Full output:"
        echo "$output"

        # Extract URLs from output
        deployment_url=$(echo "$output" | awk '/Preview:/ {print $2}')
        inspect_url=$(echo "$output" | awk '/Inspect:/ {print $2}')

        echo "Extracted deployment URL: $deployment_url"
        echo "Extracted inspect URL: $inspect_url"

        # Set outputs
        echo "deployment-url=$deployment_url" >> $GITHUB_OUTPUT
        echo "inspect-url=$inspect_url" >> $GITHUB_OUTPUT

        # Only exit with error if deployment actually failed (no URLs found)
        if [ -z "$deployment_url" ] && [ -z "$inspect_url" ]; then
          echo "Deployment failed - no URLs found"
          exit 1
        fi

    - name: Deploy to Vercel (production)
      id: deploy-production
      if: ${{ inputs.environment == 'production' }}
      shell: bash
      run: |
        set +e  # Don't exit on error
        output=$(pnpm dlx vercel@latest deploy --prebuilt --prod --token "$VERCEL_TOKEN" 2>&1)
        exit_code=$?
        set -e  # Re-enable exit on error

        echo "Exit code: $exit_code"
        echo "Full output:"
        echo "$output"

        # Extract URLs from output - production might use different labels
        deployment_url=$(echo "$output" | awk '/Preview:/ {print $2}')
        inspect_url=$(echo "$output" | awk '/Inspect:/ {print $2}')

        # For production, also try to get the production URL from the last line
        if [ -z "$deployment_url" ]; then
          deployment_url=$(echo "$output" | grep -E "https://.*\.vercel\.app" | tail -1)
        fi

        echo "Extracted deployment URL: $deployment_url"
        echo "Extracted inspect URL: $inspect_url"

        # Set outputs
        echo "deployment-url=$deployment_url" >> $GITHUB_OUTPUT
        echo "inspect-url=$inspect_url" >> $GITHUB_OUTPUT

        # Only exit with error if deployment actually failed (no URLs found)
        if [ -z "$deployment_url" ] && [ -z "$inspect_url" ]; then
          echo "Deployment failed - no URLs found"
          exit 1
        fi

    - name: Comment on PR
      if: ${{ github.event_name == 'pull_request' && inputs.environment != 'production' }}
      uses: actions/github-script@v7
      with:
        script: |
          const deploymentUrl = '${{ steps.deploy-preview.outputs.deployment-url }}';
          const inspectUrl = '${{ steps.deploy-preview.outputs.inspect-url }}';

          const comment = `## 🚀 Deployment Complete

          **Preview URL:** ${deploymentUrl}
          **Deployment details:** ${inspectUrl}

          Deployed from commit: ${context.sha.substring(0, 7)}`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
